title: Octopus
email: nachi.r@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Nachi. Im a Software Development Engineer from a Comp Sci Background, an
  amateur photographer and artist, and a hobbyist pianist.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "nachi.one" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: onenachi
instagram_username: thenachi
github_username:  onenachi
telegram_username: KawaiiVoldemort

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
  index:
    output: true
  sketches:
    output: true
  photos:
    output: true
  code:
    output: true